// <auto-generated />
using System;
using EFCoreCodeFirstApproach.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreCodeFirstApproach.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20211123062054_CreateLibraryDb")]
    partial class CreateLibraryDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EFCoreCodeFirstApproach.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bookid")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("bookname");

                    b.Property<int?>("memberid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("memberid");

                    b.ToTable("bookrecords");
                });

            modelBuilder.Entity("EFCoreCodeFirstApproach.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("membername");

                    b.HasKey("Id");

                    b.ToTable("memberrecords");
                });

            modelBuilder.Entity("EFCoreCodeFirstApproach.Models.Book", b =>
                {
                    b.HasOne("EFCoreCodeFirstApproach.Models.Member", "Member")
                        .WithMany("Books")
                        .HasForeignKey("memberid");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EFCoreCodeFirstApproach.Models.Member", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
